version: "3"

tasks:
  default:
    deps: ["main"]

  build:
    aliases: ["b"]
    cmds:
      - cmake -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -B build
      - cmake --build build

  main:
    deps: ["build"]
    cmds:
      - ./build/main.exe

  clean:
    aliases: ["c"]
    cmds:
      - 'if {{ eq OS "windows" }};
        then powershell Remove-Item -Recurse -Force build;
        else rm -rf build; fi'
